import { NextRequest, NextResponse } from "next/server";

const SYNTHESIA_API_KEY = process.env.SYNTHESIA_API_KEY;
const DEFAULT_AVATAR = process.env.SYNTHESIA_DEFAULT_AVATAR || "anna_costume1_cameraA";
const DEFAULT_BACKGROUND = process.env.SYNTHESIA_DEFAULT_BACKGROUND || null;
const IS_TEST_MODE = process.env.SYNTHESIA_TEST_MODE === "true";

export async function POST(req: NextRequest) {
    if (!SYNTHESIA_API_KEY) {
        return NextResponse.json({ error: "Synthesia API key not configured" }, { status: 500 });
    }

    try {
        const { script, title, description, avatar, background } = await req.json();

        if (!script) {
            return NextResponse.json({ error: "Script is required" }, { status: 400 });
        }

        const resolvedAvatar = avatar || DEFAULT_AVATAR;
        const resolvedBackground = background ?? DEFAULT_BACKGROUND;

        const payload = {
            test: IS_TEST_MODE,
            title: title || "Interview Briefing",
            description: description || "Generated by SynthesiaPrep",
            input: [
                {
                    scriptText: script,
                    avatar: resolvedAvatar,
                    ...(resolvedBackground ? { background: resolvedBackground } : {}),
                }
            ]
        };

        const makeRequest = () =>
            fetch("https://api.synthesia.io/v2/videos", {
                method: "POST",
                headers: {
                    "Authorization": SYNTHESIA_API_KEY,
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(payload),
            });

        let response = await makeRequest();

        // Automatic fallback to default avatar if the chosen one fails
        if (!response.ok && resolvedAvatar !== DEFAULT_AVATAR) {
            console.warn("Avatar request failed, retrying with default avatar");
            payload.input[0].avatar = DEFAULT_AVATAR;
            response = await makeRequest();
        }

        const text = await response.text();
        if (!response.ok) {
            console.error("Synthesia API Error:", text);
            return NextResponse.json({ error: "Failed to create video", details: text }, { status: response.status });
        }

        const data = JSON.parse(text);
        return NextResponse.json(data);

    } catch (error) {
        console.error("Error creating Synthesia video:", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}

